"""Deterministically generate manuscript table/figure inputs from the frozen example.

Generated files are build artifacts. Do not hand-edit them.
"""
from __future__ import annotations

from pathlib import Path
import sympy as sp

ROOT = Path(__file__).resolve().parents[1]
FIGURES = ROOT / "figures"
TABLES = ROOT / "tables"


def frozen_values():
    aL = sp.Rational(4)
    aH = sp.Rational(5)
    c = sp.Rational(1)
    bL = sp.Rational(16, 5)
    KL = sp.Rational(4)
    bH = sp.Rational(1, 2)
    KH = sp.Rational(8)
    mu = sp.Rational(13, 10)
    l = sp.simplify(bL / KL)
    d = aH - aL
    RF = sp.simplify((aH**2 - aL**2) / 2)
    hF = sp.simplify((bH + RF) / KH)
    h = sp.symbols("h", positive=True)
    p = c + d * h / (l + h)
    hM = [r for r in sp.solve(sp.Eq(KH * h, bH + RF - d * p), h) if sp.N(r) > 0][0]
    phi = sp.simplify((l + h) / 2 * p**2)
    muM = sp.simplify(phi.subs(h, hM))
    muF = sp.simplify(phi.subs(h, hF))
    hstar = [r for r in sp.solve(sp.Eq(phi, mu), h) if sp.N(r) > 0][0]
    pstar = sp.simplify(p.subs(h, hstar))
    rho = sp.simplify(KH * (hF - hstar) / (d * pstar))
    return l, hM, hstar, hF, muM, mu, muF, rho


def write_table(values) -> None:
    l, hM, hstar, hF, muM, mu, muF, rho = values
    rows = [
        ("$l$", l),
        ("$h_M$", hM),
        ("$h^*$", hstar),
        ("$h_F$", hF),
        ("$\\mu_M$", muM),
        ("$\\mu$", mu),
        ("$\\mu_F$", muF),
        ("$\\rho^*$", rho),
    ]
    lines = [
        "% AUTO-GENERATED by scripts/generate_outputs.py; DO NOT EDIT.",
        "\\begin{tabular}{lrr}",
        "\\toprule",
        "Object & Exact expression & Decimal \\\\",
        "\\midrule",
    ]
    for label, value in rows:
        exact = sp.latex(sp.simplify(value))
        decimal = f"{float(sp.N(value, 14)):.6f}"
        lines.append(f"{label} & $ {exact} $ & {decimal} \\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}", ""])
    (TABLES / "baseline_example.tex").write_text("\n".join(lines), encoding="utf-8")


def write_figure(values) -> None:
    _, _, _, _, muM, mu, muF, _ = values
    mM, m0, mF = map(float, (sp.N(muM), sp.N(mu), sp.N(muF)))
    xmax = mF + 0.30
    scale = 8.0 / xmax
    xM, x0, xF, xMax = [v * scale for v in (mM, m0, mF, xmax)]
    tex = f"""% AUTO-GENERATED by scripts/generate_outputs.py; DO NOT EDIT.
\\begin{{tikzpicture}}[x=1cm,y=1cm]
  \\draw[->] (0,0) -- ({xMax:.5f},0) node[right] {{$\\mu$}};
  \\draw ({xM:.5f},-0.10) -- ({xM:.5f},0.10) node[below=5pt] {{$\\mu_M$}};
  \\draw ({xF:.5f},-0.10) -- ({xF:.5f},0.10) node[below=5pt] {{$\\mu_F$}};
  \\draw[dashed] ({x0:.5f},0) -- ({x0:.5f},0.70) node[above] {{frozen example $\\mu$}};
  \\node at ({xM/2:.5f},0.45) {{metered}};
  \\node at ({(xM+xF)/2:.5f},0.45) {{pure-regime gap}};
  \\node at ({(xF+xMax)/2:.5f},0.45) {{flat}};
\\end{{tikzpicture}}
"""
    (FIGURES / "threshold_phase.tex").write_text(tex, encoding="utf-8")


def main() -> None:
    FIGURES.mkdir(exist_ok=True)
    TABLES.mkdir(exist_ok=True)
    values = frozen_values()
    write_table(values)
    write_figure(values)
    print("generated manuscript artifacts: PASS")


if __name__ == "__main__":
    main()
